### PR TITLE
Early stop restoration

### PR DESCRIPTION
**Pull request by MinhyukPark**
This PR restores the early stop strategy as well as enabling weighted (adjusted) bitscores on hierarchical search.

### CODE REVIEW

**Review by gillichu — CHANGES_REQUESTED** [review]
This PR aims to re-introduce the early-stop flag, as well as fix some bugs regarding existing flags. It also introduces hmm counts, and also fixes some bugs with early-stop, bitscore-adjust. 

I tested this against the current master branch. I tested with 1000M1, R0 from Vlad's dataset for all of the below runs. Please see a summary below:

1. Testing master branch with "regular" .config file. See attached file for example, but all flags are set to False. (SPFN: 0.1764; SPFP: 0.1402), so we'll compare to this number. 
2. Testing **this** branch with "regular" .config file. All flags are set to False. This throws the `Exception: Unsupported strategy`. flag. 
3. Testing **this** branch with `early-stop`, `hier-upp` and `decomp-only` flags. Runs, but sees significantly lower accuracy. (SPFN: 0.4478; SPFP: 0.4154). 
4. Testing **this** branch with `hier-upp`, `decomp-only` flags. Runs, but sees significantly lower accuracy. (SPFN: 0.4449; SPFP: 0.4166).
5. Testing **this** branch with the `bitscore-adjust` and `decomp-only` flags. Runs, but sees significantly lower accuracy. (SPFN: 0.4583; SPFP: 0.4081).
6. Testing **this** branch with the `bitscore-adjust` and `hier-upp`, and `decomp-only` flags. Runs, but sees significantly lower accuracy. (SPFN: 0.4449; SPFP: 4164). 
7. Testing **this** branch with the `bitscore-adjust`, `hier-upp`, `decomp-only` and `early-stop` flags. Runs, but sees significantly lower accuracy. (SPFN: 0.4484; SPFP: 0.4143). 

It is possible that these were not tested in the correct way. If this is the case, please let me know. 

I've attached the config files that I used to test. Note that regular2.config was the file used to run the master branch (the only change is that I added absolute paths, and a different output folder). 

[configfiles.zip](https://github.com/gillichu/sepp/files/6728770/configfiles.zip)

**Comment by MinhyukPark** [comment]
no worries.

1. I think I tested running regular UPP by taking out the [upp2] section of the config entirely with the assumption that the user wouldn’t add [upp2] if they weren’t using upp2 flags. I’ll fix the checks here. In order to run regular UPP, currently it should be possible to just give a config file you used to give to UPP and it should work. 

2. We should ignore the accuracies from the master branch. The master branch will always pick the root HMM due to the hmmsearch bug (no --tblout flag and hence no scores being parsed). In addition to that, the master branch doesn't actually run hmmsearch. It runs hmmalign instead when it's supposed to run hmmsearch.

**Comment by MinhyukPark** [comment]
Also the config files you passed in doesn't seem to be correct. I had made it so that it will always run with the --max and --tblout flag instead of having to pass in the user_options group.

**Comment by gillichu** [comment]
> no worries.
> 
> 1. I think I tested running regular UPP by taking out the [upp2] section of the config entirely with the assumption that the user wouldn’t add [upp2] if they weren’t using upp2 flags. I’ll fix the checks here. In order to run regular UPP, currently it should be possible to just give a config file you used to give to UPP and it should work.
> 2. We should ignore the accuracies from the master branch. The master branch will always pick the root HMM due to the hmmsearch bug (no --tblout flag and hence no scores being parsed). In addition to that, the master branch doesn't actually run hmmsearch. It runs hmmalign instead when it's supposed to run hmmsearch.

I'm confused by this. While I know that the master branch had this bug, I was testing the master branch's default UPP (i.e. with all flags set to False). So it should not have hit the hmmsearch bug right?

**Comment by gillichu** [comment]
> Also the config files you passed in doesn't seem to be correct. I had made it so that it will always run with the --max and --tblout flag instead of having to pass in the user_options group.

I can definitely take this group out of my config files. If you have a preferred way I should run the code/preferred config file I could use as an example, please point me to it. But before I re-run these, the reason I trusted the 17% accuracy was because that seemed more close to the accuracies we were getting before on 1000M1 (as supposed to the ~40% the current branch has).

**Comment by MinhyukPark** [comment]
My previous comment was incorrect. You're right in that master branch with all flags set to false should run the default UPP and we should trust the 17% accuracy.

Now I'm wondering how the accuracy dropped by that much using the new UPP2 strategies.

**Comment by gillichu** [comment]
With these edits, I've re-tested, with the previous config files. I also checked the output files. While there are large portions of the query sequence that seem to be "nonhomologous," it looks more reasonable. 

- regular: still doesn't work, due to previously discussed reasons. This still needs to be updated before merging. 
- earlyStop: SPFN: 0.185, SPFP 0.1375.
- hier: SPFN 0.1812, SPFP 0.1393. 
- weighted: SPFN 0.2119, SPFP: 0.1388.
- hierweight: SPFN 0.1806, SPFP 0.1385.
- all:

**Pull request merged**
